config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'static_pages/home'
  get 'static_pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lynn_photos
  root 'static_pages#home'

  get "/nextPhoto" => "static_pages#next_photo", as: "nextPhoto"
  get "/previousPhoto" => "static_pages#previous_photo", as: "previousPhoto"
  post "/write_mail" => "static_pages#write_mail", as: "writeMail"
  post "/write_simple_mail" => "static_pages#write_simple_mail", as: "writeSimpleMail"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lynn_photo.rb
class LynnPhoto < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :registerable: terugzetten wanneer inschrijven mogelijk!
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lynn_photos_controller.rb
class LynnPhotosController < ApplicationController
  def index
    @lynn_photos = LynnPhoto.all
    respond_to do |format|
      format.js { render "index" }      
      format.html {  }
    end
  end

  def show
    @lynn_photo = LynnPhoto.find(params[:id])
    respond_to do |format|
      format.js { render "show", :locals => {:id => @lynn_photo.id} }      
      format.html {  }
    end
  end

  def new
    @lynn_photo = LynnPhoto.new
  end

  def create
    @lynn_photo = LynnPhoto.new(lynn_photo_params)
    @lynn_photo.save
  end

  def edit
    @lynn_photo = LynnPhoto.find(params[:id])
  end

  def update
    @lynn_photo = LynnPhoto.find(params[:id])
    LynnPhoto.update(lynn_photo_params)
  end
  
  def destroy
    puts "let us destroy, amen"
    @lynn_photo = LynnPhoto.find_by(id: params[:id])
    @lynn_photo.destroy!
    redirect_to lynn_photos_path
  end

  private

  def lynn_photo_params
    params.require(:lynn_photo).permit(:photo, :year, :city_taken, :country_taken)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  $current_photo = LynnPhoto.all.first

  def home
    # binding.pry
    load_photo
    @lynn_photo = $current_photo
    respond_to do |format|
      format.html { }
      format.js { }
    end
  end

  def next_photo
    # binding.pry
    $current_photo = next_photo_for($current_photo)
    # load_photo
    @lynn_photo = $current_photo
    # render 'static_pages/home'
    respond_to do |format|
      format.js { }
      format.html { redirect_to root_path, turbolinks: false }
    end
  end

  def previous_photo
    $current_photo = previous_photo_for($current_photo)
    @lynn_photo = $current_photo
    # render 'static_pages/home'
    respond_to do |format|
      format.js { }
      format.html { redirect_to root_path, turbolinks: false }
    end
  end

  def about
  end

  def write_mail
    puts params[:anything]
    to_mail = "dany.buts@gmail.com"
    from_mail = params[:anything]["from_mail"]
    from_name = params[:anything]["from_name"]
    from_text = params[:anything]["comment"]
    puts from_text
    picture_ids = params[:anything]["selection"].split("-")
    LynnMailer.order(from_mail,to_mail,"I am interested in your photo's",from_name,picture_ids,from_text).deliver_now
    LynnMailer.order(to_mail,from_mail,"Your mail to Lynn Raeymaekers",from_name,picture_ids,from_text).deliver_now
  end

  private
  def next_photo_for(photo)
    next_photo = LynnPhoto.where("id > ?", photo.id).first
    if !next_photo.nil?
      return next_photo
    else
      return LynnPhoto.all.first
    end
  end

  def previous_photo_for(photo)
    previous_photo = LynnPhoto.where("id < ?", photo.id).last
    if !previous_photo.nil?
      return previous_photo
    else
      return LynnPhoto.all.last
    end
  end

  def load_photo
    $current_photo = LynnPhoto.find_by(id: $current_photo_id)
    if $current_photo.nil?
      $current_photo_id = LynnPhoto.all.first.id.to_i
      $current_photo = LynnPhoto.find_by(id: $current_photo_id)
    end
    puts "lynnphoto_id is nu #{$current_photo_id} en #{$current_photo.id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lynn_photos_helper.rb
module LynnPhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lynn Raeymaekers photography</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1, shrink-to-fit=no">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Fira+Sans:300,400,500,600|Montserrat:200,300,400&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>

<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>

</body>
</html>

app/views/lynn_photos/_form.html.erb
<%= form_for(lynn_photo) do |f| %>
  <%= f.label :year %>
  <%= f.text_field :year %>

  <%= f.label :city_taken %>
  <%= f.text_field :city_taken %>

  <%= f.label :country_taken %>
  <%= f.text_field :country_taken %>

  <%= f.file_field :photo, accept: 'image/png,image/jpeg'%>

  <%= f.submit %>
<% end %>

app/views/lynn_photos/index.html.erb
<script>
  const toggleLike = (likeDiv) => {
    let i = likeDiv.querySelector('i');
    i.classList.toggle('far');
    i.classList.toggle('fas');
    if (i.classList.contains('fas')) i.style.color='rgba(150,0,0,.6)'; else i.style.color='#AAA';
  };
  const makeOrder = (orderButtonDiv) => {
    selection = ''
    document.querySelectorAll(".lynnphotosContainer .photoContainer").forEach((photoCont) => {
      if (photoCont.querySelector(".likeDiv i").classList.contains("fas"))
        selection += photoCont.querySelector(".idDiv").textContent.trim() + '-'
    });
    return selection;
  }
</script> 

<div class="bodyContainer">
  <div class="photoFullScreen">
    <div class="photoBG"></div>
  </div>
  <%= render 'components/navbar', home: false %>

  <div class="orderFramesDiv">
    <h2>Prints</h2>
    <div class="flex">
      <div class="left">
      <p>
      All photo’s on my site are available for sale. I print them on Photo Matt Fibre. </p>
      <p>
       I can send you just the picture or a framed picture with additional matting in black or white as you prefer. In the example you can see one picture with a black frame. 
       The picture size is now 27x18cm.     
     </p>
     <p>Please contact me for more information.</p>
   </div>
   <div class="right">
     <%= cl_image_tag "vaste%20fotos/kader_met_foto_voorbeeld_cropped.jpg", crop: :fill %>
   </div>
 </div>

 <h2>Overview</h2>
 <p>Click a picture to view it in full frame.</p>
 <div class="lynnphotosContainer">
  <% @lynn_photos.each do |lphoto| %>
  <div class="photoContainer">
    <%= link_to lynn_photo_path(lphoto), remote: true do %>
    <%= cl_image_tag lphoto.photo, height: 250, crop: :fill %>
    <% end %>
    <div class="bottomLine">
      <p class="idDiv" style="display:none"> <%= lphoto.id %></p>
      <p>photo: <%= lphoto.city_taken %>, <%= lphoto.country_taken %> <%= lphoto.year %> <br> <em style="color:#999">reference: <%= lphoto.id %></em></p>
      <div class="icons">
        <!--     <div class="likeDiv" onclick="toggleLike(this);">
            <i class="far fa-heart" style="color:#AAA"></i>
          </div> -->
          <% if !current_user.nil? %>
          <%= link_to lynn_photo_path(lphoto), method: :delete do %>
          <i class="fas fa-trash"></i>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <!-- <hr> -->
  <div class="contact orderContact">
    <h2>Contact Lynn about ordering the selected pictures</h2>
    <p>Leave your coordinates and Lynn will answer to you shortly.</p>
    <%= form_for :anything, :url => url_for(:controller => 'static_pages', :action => 'write_mail'),
    :html => { :id => "writeMailForm" } do |f| %>
    <%= f.hidden_field :selection, value: ''%>
    <div class="formrow">
      <%= f.label :your_name %>
      <%= f.text_field(:from_name)%>
    </div>
    <div class="formrow">
      <%= f.label :your_mail %>
      <%= f.text_field(:from_mail)%>
    </div>
    <div class="formrow">
      <%= f.label :your_message %>
      <%= f.text_area(:comment, size: "30x10")%>
    </div>

    <%= f.submit 'should be hidden', id:'sendSelection' %>
    <% end %>
    <div class="orderButtonDiv">
      <div class="orderButton" onclick="document.querySelector('#anything_selection').value=makeOrder(this); document.querySelector('#writeMailForm').submit();">
        send
      </div>
    </div>
  </div>

</div>


</div>

app/views/lynn_photos/index.js.erb
console.log("yes");

app/views/lynn_photos/new.html.erb
<%= render 'form', lynn_photo: @lynn_photo %>

app/views/lynn_photos/show.html.erb
<%= @lynn_photo.city_taken %>
<%= cl_image_tag @lynn_photo.photo, height: 300, width: 400, crop: :fill %>

app/views/lynn_photos/show.js.erb
lynnphotoid = <%= id %>
// alert ("marcheert, we tonen photo id" + lynnphotoid);
fullscreenDiv = document.querySelector(".photoFullScreen");
document.querySelector(".orderFramesDiv").style.display = "none";
fullscreenDiv.style.display="block";
photoBG = document.querySelector(".photoBG");
photoBG.style.backgroundImage = "url('<%= cl_image_path @lynn_photo.photo, height: 1021, crop: :fit %>')";
photoBG.style.backgroundPosition = "center";
photoBG.style.backgroundRepeat = "no-repeat";
photoBG.addEventListener("click",(e)=> {
  fullscreenDiv.style.display = "none";
  document.querySelector(".orderFramesDiv").style.display = "block";
});
photoBG.querySelector(".likeDiv").addEventListener("click",(e)=>{
  let i = photoBG.querySelector(".likeDiv i");
  i.classList.toggle("far");
  i.toggle("fas");
});

app/views/static_pages/about.html.erb
<%= render 'components/navbar', home: false %>

<div class="aboutLynnDiv">

  <h2>About</h2>


  <p>My pictures are stories in a photograph. I learned the art of storytelling being an editor for more than 20 years. You need a sharp eye for detail when editing a film or a television program. I really hope that you also enjoy particular details in my pictures as I do. The world is full of them and during my travels I try to capture them with my compact Panasonic DMC-GM1.
  </p>

  <p>You can also follow me on <%= link_to 'instagram', "https://www.instagram.com/lynnraey_travel/" %>.</p>

  <h2>Contact</h2>
  <div class="contact">
    <div class="contactrow" style="display:none">  <div class="iconDiv"><i class="fas fa-mobile-alt"></i></div> 0032 489 56 93 05  </div>
    <div class="contactrow">  <div class="iconDiv"><i class="far fa-envelope"></i> </div> <a href="mailto:lynnraeyphoto@gmail.com">lynnraeyphoto@gmail.com</a></div>
  </div>
  <div class="contact simple" style="display:none">
    <%= form_for :anything, :url => url_for(:controller => 'static_pages', :action => 'write_simple_mail'),
    :html => { :id => "writeSimpleMailForm" } do |f| %>
    <div class="formrow">
      <%= f.label :your_name %>
      <%= f.text_field(:from_name)%>
    </div>
    <div class="formrow">
      <%= f.label :your_mail %>
      <%= f.text_field(:from_mail)%>
    </div>
    <div class="formrow">
      <%= f.label :your_message %>
      <%= f.text_area(:comment, size: "30x10")%>
    </div>
    <%= f.submit 'should be hidden', id:'sendSelection', class:'orderButton' %>
    <% end %>
  </div>
</div>



</div>

app/views/static_pages/home.html.erb
<%= render 'components/navbar', home: true %>


<% cl_url = cl_image_path @lynn_photo.photo, height: 750, crop: :limit, :quality=>"auto:low" %>
<% puts "new url: #{cl_url}" %>

<div class="mainPhoto" style="background-image:url('<%= cl_url %>'), linear-gradient(to bottom, #FFF, #DDD 75%);">

  <div class="leftBtn btnColumn">
    <%= link_to previousPhoto_path(photo_id: @lynn_photo.id), remote: true do %>
    <i class="fas fa-caret-left"></i>
    <% end %>
  </div>
  <div class="middlePart">
  </div>
  <div class="rightBtn btnColumn">
    <%= link_to nextPhoto_path(photo_id: @lynn_photo.id), remote: true do %>
    <i class="fas fa-caret-right"></i>
    <% end %>
  </div>
</div>

<%= render 'components/footer' %>

<script>
  y = setInterval(function(){ console.log("click"); document.querySelector(".rightBtn a").click(); }, 13000);
  document.querySelector(".rightBtn a").addEventListener("click", () => {clearInterval(y);
    y = setInterval(function(){ console.log("click"); document.querySelector(".rightBtn a").click(); }, 13000);
  });
  document.querySelector(".leftBtn a").addEventListener("click", () => {clearInterval(y);
    y = setInterval(function(){ console.log("click"); document.querySelector(".rightBtn a").click(); }, 13000);
  });
  document.addEventListener("keydown", (event) => {
    console.log("key!");
    switch (event.key) {
      case "ArrowLeft":
      // clearInterval(y);
      document.querySelector(".leftBtn a").click();
      break;
      case "ArrowRight":
      // clearInterval(y);
      document.querySelector(".rightBtn a").click();

      break;
      case "ArrowUp":
      // clearInterval(y);
      // document.querySelector(".leftBtn a").click();
      break;
      case "ArrowDown":
      // clearInterval(y);
      document.querySelector(".rightBtn a").click();
      break;
    }
  });
  document.querySelector(".middlePart").addEventListener("click", () => {
    const navBar = document.querySelector(".navbar");
    navBar.classList.toggle("hideDiv");
    const mainPhoto = document.querySelector(".mainPhoto");
    if (navBar.classList.contains("hideDiv")) {
      mainPhoto.style.backgroundSize = "contain";
      mainPhoto.style.marginLeft = "0";
      mainPhoto.style.marginRight = "0";


    } else {
      mainPhoto.style.backgroundSize = "cover";
      let marVar="20vh";
      if (window.innerWidth < 1024) marVar = "4vw";
      mainPhoto.style.marginLeft = marVar;
      mainPhoto.style.marginRight = marVar;

    }
    document.querySelector(".footer").classList.toggle("hideDiv");

  });

</script>

app/views/static_pages/next_photo.js.erb
document.querySelectorAll(".mainPhoto").forEach((mp) => {
  mp.style.opacity = 0;

  setTimeout(function () {
    mp.style.backgroundImage = "url(<%= cl_image_path @lynn_photo.photo, crop: :fill %>), linear-gradient(to bottom, #FFF, #DDD 75%)";
    mp.style.opacity=1;
    }, 700);
});

document.querySelectorAll(".picInfoText").forEach((picinf) => {
  picinf.innerText = "<%= @lynn_photo.city_taken %> , <%= @lynn_photo.country_taken %> "
});

app/views/static_pages/previous_photo.js.erb
document.querySelectorAll(".mainPhoto").forEach((mp) => {
  
  mp.style.opacity = 0;
  setTimeout(function () {
      mp.style.backgroundImage = "url(<%= cl_image_path @lynn_photo.photo, crop: :fill %>), linear-gradient(to bottom, #FFF, #DDD 75%)";
      mp.style.opacity=1;
  }, 700);
});

document.querySelectorAll(".picInfoText").forEach((picinf) => {
  picinf.innerText = "<%= @lynn_photo.city_taken %> , <%= @lynn_photo.country_taken %> "
});

app/views/static_pages/write_mail.html.erb
<%= render 'components/navbar', home: true %>

<div class="mailConfirm">
<h2>Your mail has been sent</h2>
<p> and a copy of this mail has been sent to your mailbox. Lynn will be in touch!</p>
<%= link_to "home", root_path %>
</div>